package com.duperknight.client.utils;

import com.duperknight.client.session.CommandDispatch;
import com.duperknight.client.session.ConnectionSnapshot;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.message.v1.ClientReceiveMessageEvents;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents;
import net.minecraft.client.MinecraftClient;
import net.minecraft.text.Text;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Locale;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Sends module chat in public/global chat while preserving the player's active channel. */
public final class GlobalChatMessenger {
    private static final String PREFIX = "§8[§6DMLS - Chat§8] §7";
    private static final String CHANNELS_LIST_COMMAND = "channels list";
    private static final String PUBLIC_CHANNEL = "public";
    private static final int RESPONSE_TIMEOUT_TICKS = 60;
    private static final int RESPONSE_QUIET_TICKS = 4;
    private static final int ACTION_DELAY_TICKS = 2;
    private static final Pattern LIST_HEADER = Pattern.compile("(?i)^channel\\s+list\\s*:?$");
    private static final Pattern STATUS_LINE = Pattern.compile(
            "(?i)^([A-Za-z0-9_-]+)\\s+status\\s*:\\s*(transmitting|receiving)\\s*$");

    private static final Deque<Request> QUEUE = new ArrayDeque<>();
    private static ActiveSend active;
    private static boolean registered;

    private GlobalChatMessenger() {
    }

    public static void register() {
        if (registered) return;
        registered = true;
        ClientReceiveMessageEvents.ALLOW_GAME.register((message, overlay) -> allowMessage(message));
        ClientReceiveMessageEvents.ALLOW_CHAT.register((message, signed, sender, params, timestamp) -> allowMessage(message));
        ClientTickEvents.END_CLIENT_TICK.register(GlobalChatMessenger::tick);
        ClientPlayConnectionEvents.DISCONNECT.register((handler, client) -> reset());
    }

    public static CommandDispatch dispatch(
            MinecraftClient client,
            String message,
            boolean dryRunCaptured,
            ConnectionSnapshot expectedConnection
    ) {
        if (dryRunCaptured) {
            return ClientUtils.dispatchChatMessageDirect(client, message, true, expectedConnection);
        }
        if (message == null || message.isBlank() || expectedConnection == null
                || !expectedConnection.matches(client) || !ServerGuard.check(client).allowed()) {
            return CommandDispatch.BLOCKED;
        }

        Request request = new Request(message, expectedConnection);
        if (active == null) {
            return start(client, request);
        }
        QUEUE.addLast(request);
        return CommandDispatch.SENT;
    }

    private static CommandDispatch start(MinecraftClient client, Request request) {
        CommandDispatch query = ClientUtils.dispatchCommand(
                client, CHANNELS_LIST_COMMAND, false, request.connection);
        if (query != CommandDispatch.SENT) return query;
        active = new ActiveSend(request);
        return CommandDispatch.SENT;
    }

    private static boolean allowMessage(Text message) {
        if (active == null || active.stage != Stage.QUERYING) return true;
        Optional<ChannelListLine> parsed = parseChannelListLine(ChatUtils.cleanLine(message.getString()));
        if (parsed.isEmpty()) return true;

        ChannelListLine line = parsed.get();
        active.sawResponse = true;
        active.quietTicks = RESPONSE_QUIET_TICKS;
        if (line.kind == LineKind.TRANSMITTING) {
            active.previousChannel = line.channel;
        }
        // Consume only the channel-list response generated by our active query.
        return false;
    }

    private static void tick(MinecraftClient client) {
        if (active == null) return;
        if (!active.request.connection.matches(client)) {
            reset();
            return;
        }

        switch (active.stage) {
            case QUERYING -> tickQuery(client);
            case WAITING_TO_SEND -> {
                if (--active.delayTicks <= 0) sendMessage(client);
            }
            case WAITING_TO_RESTORE -> {
                if (--active.delayTicks <= 0) restoreChannel(client);
            }
        }
    }

    private static void tickQuery(MinecraftClient client) {
        active.elapsedTicks++;
        if (active.sawResponse) {
            if (--active.quietTicks <= 0) {
                prepareToSend(client);
            }
            return;
        }
        if (active.elapsedTicks >= RESPONSE_TIMEOUT_TICKS) {
            ChatUtils.sendTranslatedMessage(client, PREFIX, "dmls.chat.global_channel.query_failed");
            finish(client);
        }
    }

    private static void prepareToSend(MinecraftClient client) {
        String previous = active.previousChannel;
        if (previous == null || isPublicChannel(previous)) {
            active.stage = Stage.WAITING_TO_SEND;
            active.delayTicks = 1;
            return;
        }

        CommandDispatch switched = ClientUtils.dispatchCommand(
                client, "talkon " + PUBLIC_CHANNEL, false, active.request.connection);
        if (switched != CommandDispatch.SENT) {
            ChatUtils.sendTranslatedMessage(client, PREFIX, "dmls.chat.global_channel.switch_failed");
            finish(client);
            return;
        }
        active.stage = Stage.WAITING_TO_SEND;
        active.delayTicks = ACTION_DELAY_TICKS;
    }

    private static void sendMessage(MinecraftClient client) {
        CommandDispatch sent = ClientUtils.dispatchChatMessageDirect(
                client, active.request.message, false, active.request.connection);
        if (sent != CommandDispatch.SENT) {
            ChatUtils.sendTranslatedMessage(client, PREFIX, "dmls.chat.global_channel.send_failed");
            if (active.previousChannel != null && !isPublicChannel(active.previousChannel)) {
                restoreChannel(client);
            } else {
                finish(client);
            }
            return;
        }

        if (active.previousChannel == null || isPublicChannel(active.previousChannel)) {
            finish(client);
            return;
        }
        active.stage = Stage.WAITING_TO_RESTORE;
        active.delayTicks = ACTION_DELAY_TICKS;
    }

    private static void restoreChannel(MinecraftClient client) {
        String previous = active.previousChannel;
        if (previous != null && !isPublicChannel(previous)) {
            CommandDispatch restored = ClientUtils.dispatchCommand(
                    client, "talkon " + previous, false, active.request.connection);
            if (restored != CommandDispatch.SENT) {
                ChatUtils.sendTranslatedMessage(client, PREFIX,
                        "dmls.chat.global_channel.restore_failed", previous);
            }
        }
        finish(client);
    }

    private static void finish(MinecraftClient client) {
        active = null;
        while (!QUEUE.isEmpty() && active == null) {
            Request next = QUEUE.removeFirst();
            if (!next.connection.matches(client)) continue;
            if (start(client, next) != CommandDispatch.SENT) {
                ChatUtils.sendTranslatedMessage(client, PREFIX, "dmls.chat.global_channel.query_failed");
            }
        }
    }

    private static void reset() {
        active = null;
        QUEUE.clear();
    }

    static Optional<ChannelListLine> parseChannelListLine(String line) {
        if (line == null) return Optional.empty();
        String clean = line.trim();
        if (LIST_HEADER.matcher(clean).matches()) {
            return Optional.of(new ChannelListLine(LineKind.HEADER, ""));
        }
        Matcher matcher = STATUS_LINE.matcher(clean);
        if (!matcher.matches()) return Optional.empty();
        LineKind kind = matcher.group(2).equalsIgnoreCase("transmitting")
                ? LineKind.TRANSMITTING
                : LineKind.RECEIVING;
        return Optional.of(new ChannelListLine(kind, matcher.group(1)));
    }

    static boolean isPublicChannel(String channel) {
        if (channel == null) return true;
        String normalized = channel.replace("_", "").replace("-", "").toLowerCase(Locale.ROOT);
        return normalized.equals("public") || normalized.equals("global") || normalized.equals("globalchat");
    }

    enum LineKind {
        HEADER,
        TRANSMITTING,
        RECEIVING
    }

    record ChannelListLine(LineKind kind, String channel) {
    }

    private enum Stage {
        QUERYING,
        WAITING_TO_SEND,
        WAITING_TO_RESTORE
    }

    private record Request(String message, ConnectionSnapshot connection) {
    }

    private static final class ActiveSend {
        private final Request request;
        private Stage stage = Stage.QUERYING;
        private String previousChannel;
        private int elapsedTicks;
        private int quietTicks;
        private int delayTicks;
        private boolean sawResponse;

        private ActiveSend(Request request) {
            this.request = request;
        }
    }
}
